### ISSUE TITLE
Demo Projects Look different in Editor/Player than as standalone projects. 

### ISSUE THREAD

**Issue by Luxapodular** [WickOnline/wick#176]
[https://www.youtube.com/watch?v=n4lxUvaIcuM&feature=youtu.be](url) <--- Video

**Comment by zrispo** [comment]
haha woah i have no idea

**Comment by zrispo** [comment]
do images render incorrectly or is it just vectors

**Comment by zrispo** [comment]
This is a problem with caching the SVGs , rasterizing doesn't take into account window.devicePixelRatio breaking them for retina displays
