### ISSUE TITLE
Sounds won't play if playSound is called and the sound isn't fully loaded, so sounds played soon after the project is run get skipped

### ISSUE THREAD

**Issue by zrispo** [WickOnline/wick#212]

**Comment by Luxapodular** [comment]
We probably need to introduce some form of a preloader. Like this puppy! 
![image](https://cloud.githubusercontent.com/assets/8699557/19706679/2d0e2cfc-9ae1-11e6-99f6-22414d5c913f.png)

**Comment by zrispo** [comment]
added a hack to fix this for now, but yea we need preloaderz
