### ISSUE TITLE
Copy/Paste cross-browser compatability

### ISSUE THREAD

**Issue by Luxapodular** [WickOnline/wick#40]
Using version 9.0.1 (11601.2.7.2). I think that the current "Focus" trick we are using is not applicable to Safari... I'll poke around a bit and try to find an equivalent fix.

**Comment by zrispo** [comment]
I got the code from here: http://jsfiddle.net/vtjnr6ea/

They have a specific thing for safari that I didn't implement yet, gotta do that

**Comment by zrispo** [comment]
Copy paste doesn't work on firefox either!

Google docs can do it in all browsers (not sure abt IE obv.) so we should be able to figure it out
